Сделал HTML верстку мобильной версии
htmlacademy-adaptive/1814289-cat-energy-23 pull request #2
Opened 2021-07-26 07:16 UTC by Ivanrumanchev

2021-07-26 11:06 UTC, Ivanrumanchev commented
В футере нашел ошибочку что неправильно классы социальных сетей названы, во всех страницах исправил с social__link social__link__vk на social__link social__link--vk

2021-07-26 11:25 UTC, Ivanrumanchev commented
Также в файле catalog.html убрал пустые доп ссылки <a name=''"></a> (на строчках 49 и 133) для быстрого перехода к разделу из index.html и просто добавил этот атрибут к ссылке на 47 строчке и 131

2021-07-26 17:19 UTC, 4err requested changes
Отличная работа!
По заданию необходимо выполнить было только разметку главной страницы. 
Один пуллреквест решает одну задачу. Не следует смешивать задачи.

2021-07-26 17:19 UTC, 4err commented on source/catalog.html
> +                <img class="catalog__img" src="img/catalog-1-desktop1.png" alt="Cat Energy PRO 500 г курица">
Давай исправим имена изображений так, чтобы они отражали суть изображения.

2021-07-26 17:19 UTC, 4err commented on source/catalog.html
> +              <li class="extra__item">
Тут вероятно тоже отдельный бэм блок.

2021-07-26 17:19 UTC, 4err commented on source/catalog.html
> +            <legend class="extra__legend">Дополнительные товары</legend>
Филдсет и легенда это все-таки часть формы.

2021-07-26 17:19 UTC, 4err commented on source/catalog.html
> +            Закажите все <br>
Старайся не использовать br без необходимости. Контент менеджер не будет их расставлять.

2021-07-26 17:19 UTC, 4err commented on source/form.html
> +            <input class="contacts-person__input" type="email" name="mail" id="mail" placeholder="KUKLACHEV@GMAIL.COM" required>
А чем этот инпут принципиально отличается от инпута с фио? В форме нужны классы не по контенту, а по типам элементов. Это касается всех блоков формы.

2021-07-26 19:22 UTC, Ivanrumanchev commented on source/catalog.html
> +                <a href="">Каталог продукции</a>
то есть ссылок на страницу (атрибута href), на которой находишься быть не должно? Получается и в логотипе на главной тоже нужно убрать href?

2021-07-26 19:22 UTC, Ivanrumanchev commented on source/catalog.html
> +            <li class="catalog__item">
Насколько я понял, необходимо обернуть содержание всего тега <li> в тег <article>. Для него подойдёт класс .item? в остальные классы тегов внутри этого блока соответственно необходимо переименовать (было <a class="catalog__link"> стало <a class="item__link"> и так далее все catalog__ заменить на item__) так?

2021-07-26 19:27 UTC, Ivanrumanchev commented on source/catalog.html
> +              <a class="catalog__link" href="#" name="fat">
Этот атрибут я использовал чтобы можно было перейти с главной страницы по ссылке прямо к нужному разделу каталога (страница index.html строка 61 `<a class="targets__to-catalog" href="catalog.html#slim">КАТАЛОГ SLIM</a>`). Это нужно как-то иначе сделать?

2021-07-26 19:31 UTC, Ivanrumanchev commented on source/catalog.html
> +            <li class="catalog__item">
точнее даже, наверное, `<article class="catalog-item">`, чтобы в блоке дополнительных товаров не повторялись названия классов(блоков)

2021-07-26 19:33 UTC, Ivanrumanchev commented on source/catalog.html
> +              <li class="extra__item">
`<article class="extra-item">` подойдёт? И так же все вложенные классы тоже переименовать с extra__ на extra-item__

2021-07-26 19:37 UTC, Ivanrumanchev commented on source/catalog.html
> +            <legend class="extra__legend">Дополнительные товары</legend>
подскажи пожалуйста, каким образом лучше сделать выделение названия блока таким образом, как на макете? как будто бы легенда для филдсета (название поверх линии)

2021-07-26 20:03 UTC, Ivanrumanchev commented on source/form.html
> +            <input class="contacts-person__input" type="email" name="mail" id="mail" placeholder="KUKLACHEV@GMAIL.COM" required>
Ты имеешь ввиду, что можно создать отдельные блоки с классами `.input-text` для текстовых полей, `.input-checkbox` для чекбоксов и `.input-radio` для радиокнопок, и отдельный блок с классом `.label` ко всем тегам `<label>` и всем тегам их примиксовать? 
Ещё вопросик, стоит ли переделывать разделение: 
`<label class="contacts-person__label label" for="mail">E-MAIL:*</label>
  <input class="contacts-person__input input-text" type="email" name="mail" id="mail" placeholder="KUKLACHEV@GMAIL.COM" required>`
  
            на 
            
            `<label class="contacts-person__label label">E-MAIL:*
            <input class="contacts-person__input input-text" type="email" name="mail" placeholder="KUKLACHEV@GMAIL.COM" required>
              </label>`
          Чтобы уйти от for и id? Может потом ещё и удобнее будет сетку делать?

2021-07-27 06:03 UTC, 4err commented on source/catalog.html
> +                <a href="">Каталог продукции</a>
Все верно. При отсутствии href браузер и поисковики понимают, что сейчас этот элемент не является ссылкой, но вообще это часть навигации и индексирует соответствующим образом. Это же касается и всяких страниц в каталогах и прочем. Везде где ссылка ведет на текущую же страницу.

2021-07-27 06:04 UTC, 4err commented on source/catalog.html
> +            <li class="catalog__item">
Все верно

2021-07-27 06:04 UTC, 4err commented on source/catalog.html
> +              <a class="catalog__link" href="#" name="fat">
Аргумент, можешь оставить.

2021-07-27 06:05 UTC, 4err commented on source/catalog.html
> +              <li class="extra__item">
Вполне

2021-07-27 06:07 UTC, 4err commented on source/catalog.html
> +            <legend class="extra__legend">Дополнительные товары</legend>
Обычная стилизация. Псевдоэлементы, отступы. Также тут можно попробовать использовать градиент с жестким переходом и белый фон под текстом, создастся нужный эффект.

2021-07-27 06:09 UTC, 4err commented on source/form.html
> +            <input class="contacts-person__input" type="email" name="mail" id="mail" placeholder="KUKLACHEV@GMAIL.COM" required>
>Ты имеешь ввиду, что можно создать отдельные блоки с классами .input-text для текстовых полей, .input-checkbox для чекбоксов и .input-radio для радиокнопок, и отдельный блок с классом .label ко всем тегам <label> и всем тегам их примиксовать?

Можно отдельными блоками, а можно и элементами формы. Просто у тебя будет несколько видов элементов, тут ты сам определяешь что тебе больше нравится. 

С лейблами аналогично, и тот и другой вызовет разные проблемы, но подскажу, чтоб потом не переделывать, лучше оставить так :)

2021-07-27 18:57 UTC, 4err requested changes

2021-07-27 18:57 UTC, 4err commented on source/catalog.html
> +                  <img class="catalog-item__img" src="img/Cat_Energy_PRO_500_chicken.png" alt="Cat Energy PRO 500 г курица">
В именах файлов не должно быть заглавных букв.

2021-07-28 04:38 UTC, merged